Repository OSOceanAcoustics/echopop, pull requests merged in 2023-12, with the labels that each got.

#123 Use `setuptools_scm` for auto versioning
  .flake8
  .gitignore
  EchoPro/__init__.py
  condaenvironment.yaml
  pyproject.toml
  setup.cfg
Labels: design

#140 Update and correct installation instructions in README
  README.md
Labels: documentation

#147 Couple of updates to input-files doc page
  docs/input-files.md
Labels: documentation

#150 Input files page, add "Old name" column to description tables
  docs/input-files.md
Labels: documentation

#152 Ensure new reports are actually generated when `test_reports.py` tests are run
  .gitignore
  EchoPro/tests/reports/test_reports.py
Labels: tests

#154 In input files docs page, add NASC columns loaded in `reports.py`
  docs/input-files.md
Labels: documentation
