Repository OSOceanAcoustics/echopop, pull requests merged in 2024-10, with the labels that each got.

#277 Documentation for differences between `EchoPro` and `Echopop`
  docs/_config.yml
  docs/_toc.yml
  docs/echopro_vs_echopop.md
  docs/images/abundance_to_nasc_conversion.jpg
  docs/images/aged_abundance_apportionment.jpg
  docs/images/aged_aged_sex_length_age_number_proportion.jpg
  docs/images/aged_all_sex_number_proportion.jpg
  docs/images/aged_and_unaged_apportioned_sexed_abundance.jpg
  docs/images/biomass_to_abundance_conversion.jpg
  docs/images/initial_biomass_summation.jpg
  docs/images/total_apportioned_abundance.jpg
  docs/images/unaged_abundance_apportionment.jpg
  docs/images/unaged_all_sex_number_proportion.jpg
  docs/images/unaged_unaged_sex_length_number_proportion.jpg
  docs/theory/apportion_abundance.md
  docs/theory/apportion_biomass.md
Labels: documentation

#216 Create kriged apportioned abundance documentation
  docs/images/abundance_to_nasc_conversion.jpg
  docs/images/aged_abundance_apportionment.jpg
  docs/images/aged_aged_sex_length_age_number_proportion.jpg
  docs/images/aged_all_sex_number_proportion.jpg
  docs/images/aged_and_unaged_apportioned_sexed_abundance.jpg
  docs/images/biomass_to_abundance_conversion.jpg
  docs/images/core_data_structure.jpg
  docs/images/example_indexing.jpg
  docs/images/initial_biomass_summation.jpg
  docs/images/length_age_sex_stratification.jpg
  docs/images/length_age_stratification.jpg
  docs/images/length_sex_stratification.jpg
  docs/images/length_stratification.jpg
  docs/images/total_apportioned_abundance.jpg
  docs/images/unaged_abundance_apportionment.jpg
  docs/images/unaged_all_sex_number_proportion.jpg
  docs/images/unaged_unaged_sex_length_number_proportion.jpg
  docs/theory/apportion_abundance.md
  docs/theory/stratification.md
Labels: documentation

#280 Symbol change: number of fish samples, weight proportion
  docs/glossary.md
  docs/theory/apportion_biomass.md
Labels: documentation

#274 Drop haul-transect/transect-region requirements
  config_files/initialization_config.yml
  config_files/survey_year_2019_config.yml
  docs/_toc.yml
  docs/images/Echopop_input_schematic.png
  docs/implementation.md
  docs/implementation/echopro_vs_echopop.md
  docs/implementation/preprocessing_data.md
  echopop/analysis.py
  echopop/biology.py
  echopop/survey.py
  echopop/tests/test_data_loader_validation.py
  echopop/tests/test_pandera_validation.py
  echopop/utils/load.py
  echopop/utils/load_nasc.py
  echopop/utils/validate_df.py
  echopop/utils/validate_dict.py
  environment.yaml
Labels: bug_in_python, design, refactor

#283 Amendments to input files documentation
  docs/input_files.md
Labels: documentation

#291 Amend `pandera` and `pydantic` validators
  config_files/survey_year_2019_config.yml
  echopop/spatial/variogram.py
  echopop/survey.py
  echopop/tests/test_class.py
  echopop/tests/test_data_loader_validation.py
  echopop/tests/test_pandera_validation.py
  echopop/tests/test_pydantic_validation.py
  echopop/utils/validate_df.py
  echopop/utils/validate_dict.py
Labels: tests

#284 Add Jolly-Hampton stratification section
  docs/references.bib
  docs/theory/stratification.md
  docs/zbibliography.md
Labels: documentation
