Repository OSOceanAcoustics/echopop, pull requests merged in 2024-11, with the labels that each got.

#292 Add references page to sidebar
  docs/_toc.yml
Labels: documentation

#297 Amend `Survey`-class methods documentation
  config_files/initialization_config.yml
  docs/_config.yml
  docs/api.rst
  echopop/statistics.py
  echopop/survey.py
  echopop/utils/validate_dict.py
Labels: documentation

#296 Add badges to README
  README.md
Labels: documentation

#299 Add dependabot.yml
  .github/dependabot.yml
Labels: enhancement

#302 Fix kriging analysis bugs
  echopop/spatial/krige.py
  echopop/survey.py
  echopop/tests/test_pydantic_validation.py
  echopop/utils/validate_dict.py
Labels: bug_in_python

#303 Update example notebook
  docs/example_notebooks/example_echopop_workflow.ipynb
Labels: documentation

#301 Report generation
  config_files/survey_year_2019_config.yml
  docs/_toc.yml
  docs/example_notebooks/example_echopop_workflow.ipynb
  docs/example_notebooks/report_generation.ipynb
  docs/implementation/preprocessing_data.md
  echopop/extensions/__init__.py
  echopop/extensions/feat_report.py
  echopop/extensions/survey_extensions.py
  echopop/tests/test_data_loader_validation.py
  echopop/utils/validate_dict.py
  requirements.txt
Labels: documentation, enhancement, design, high_priority, FEAT

#295 Add plotting methods
  docs/_toc.yml
  docs/example_notebooks/plotting.ipynb
  echopop/graphics/plotting.py
  echopop/graphics/validate_plot.py
  echopop/survey.py
  environment.yaml
  requirements.txt
Labels: documentation, enhancement
